services:
  class-service:
    build: ./backend/class-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on: []

  grade-service:
    build: ./backend/grade-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on: []

  overview-service:
    build: ./backend/overview-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on: []

  user-service:
    build: ./backend/user-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on: []

  frontend:
    build: ./frontend/notenverwaltung-ui
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - class-service
      - grade-service
      - overview-service
      - user-service
